name: "🧪🤡 Tests con Mocks "

on:
  push:
  pull_request:

jobs:
  test:
    uses: ./.github/workflows/reusable-test-workflow.yml
    permissions:
      contents: read
      checks: write
      pull-requests: write
    with:
      test-command: "npm run test:mock"
      test-name: "Mock Tests"
      test-emoji: "🧪🤡"
      runner-emoji: "🧪"
      node-version: "20"
