name: "🧪🐳 Tests  con Test Containers"

on:
  push:
  pull_request:

jobs:
  test:
    uses: ./.github/workflows/reusable-test-workflow.yml
    with:
      test-command: "npm run test:test-containers"
      test-name: "Test-Containers"
      test-emoji: "🧪🐳"
      runner-emoji: "🧪🐳"
      node-version: "20"
      needs-postgres: false
