name: "🐳🐳 Tests con Docker Compose"

on:
  push:
  pull_request:

jobs:
  test:
    uses: ./.github/workflows/reusable-test-workflow.yml
    with:
      test-command: "npm run test:legacy:docker-compose"
      test-name: "Docker Compose Tests"
      test-emoji: "🐳🐳"
      runner-emoji: "🐳"
      node-version: "20"
      needs-postgres: false
