name: "🧪🤡 Tests con Mocks "

on:
  push:
  pull_request:

jobs:
  test:
    uses: ./.github/workflows/reusable-test-workflow.yml
    with:
      test-command: "npm run test:mock"
      test-name: "Mock Tests"
      test-emoji: "🧪🤡"
      runner-emoji: "🧪"
      node-version: "20"
      needs-postgres: false
